### PR TITLE
Add Floom - The AI Gateway

### PR DESCRIPTION
**Pull request by FloomAI**

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
Thanks for your contribution! :tada: :+1:

**Review by gaocegege — COMMENTED** [review]
Could we only put floom in the framework section?

**Comment by FloomAI** [comment]
> Could we only put floom in the framework section?

Yes :) Thanks!

**Comment by FloomAI** [comment]
@gaocegege Hi could you please merge it?
Thanks

**Pull request closed without merging**
