### PR TITLE
Added Floom

### PR DESCRIPTION
**Pull request by FloomAI**

### CODE REVIEW

**Comment by mnns** [comment]
Thanks

**Comment by mnns** [comment]
Please add Floom :-) Thanks!

**Comment by VoVAllen** [comment]
Why did you place floom in the Agent & Prompt Framework instead of the gateway & router section? I saw floom is an AI gateway on its homepage

**Comment by mnns** [comment]
> Why did you place floom in the Agent & Prompt Framework instead of the gateway & router section? I saw floom is an AI gateway on its homepage

Hi! Floom fits many categories here, but we are mostly focused on Agent & Prompt Framework.
Floom is a different approach for building prompts & agents, it also comes with an AI Gateway, and handles pipelines.
After some consideration we felt our focus is the framework section.

Thanks!

**Pull request merged**
